<title>Create a chart from a feed in the MK Data Hub</title>
 <style>
        table {
	  margin-bottom: 6px;
	  }
        .error{
           color: red;
        }
        .success{
           color: darkgreen;
        }
        #main{
          margin-left: 5%;
	  margin-right: 5%;
	    }
        * {
        font-family: Helvetica, Arial;
	box-sizing: border-box;
	font-size: 18px;
	-moz-box-sizing: border-box;
	-webkit-box-sizing: border-box;
        }
	input{
	   padding: 5px 5px 5px 5px;
	   width: 500px;
	   margin-bottom: 10px;
	}
        #header{
           width: 100%;
           background: #52bc61;
           color: #fff;
           margin: 0px 0px 10px 0px;
           font-size: 150%;
           padding: 20px;
        }
        body{
           margin: 0px;
           padding: 0px;
        }
        #form {
           padding-left: 20px;
           padding-top: 10px;
           padding-bottom: 10px;
           margin-top: 50px;
        }
        #button{
	   border: 0px;
           background: #52bc61;
           color: #fff;
           padding: 7px;
           border-radius: 5px;        
	   }
        #footer{
            position: absolute;
            bottom: 0px;
            left:0px; 
            background: #636466;
            font-size: 80%; 
	        padding: 10px;
            width: 100%;
            color: #ddd;
        }  
        #footer a {
           color: #008bc6;

        }
        </style>
</head>

<body>

<div id="header">
<h1 style="font-size: 20px">Create a chart from a feed in the MK Data Hub</h1>
</div>