<title>MK Data Hub - Chart</title>
<script type="text/javascript" src="canvas/canvasjs.min.js"></script>
</head>
<style>
        * {
        font-family: Helvetica, Arial;
	box-sizing: border-box;
	font-size: 18px;
	-moz-box-sizing: border-box;
	-webkit-box-sizing: border-box;
        }
        #message{
          font-size: 20px;
	  color: #993333;
	  text-align: center;
	  width: 100%;
	  position: absolute;
	  top: 20%; 
        }
</style>
<body>

<?php
?>